### ISSUE TITLE
RGBA raw writer

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dirkvdb/ffmpegthumbnailer#101]
```
Sometimes, I want to know rgb value from the file. 
My attachment is related to RawWriter which can store RGBA image.


```

Original issue reported on code.google.com by `justin.j...@gmail.com` on 15 Feb 2013 at 12:10

Attachments:
- [patch0.patch](https://storage.googleapis.com/google-code-attachments/ffmpegthumbnailer/issue-101/comment-0/patch0.patch)

**Comment by tomaszg7** [comment]
I was just trying to use FFmpegthumbnailer in https://github.com/BestImageViewer/geeqie and it would be very helpful to see this feature. Especially using library, it is often counterproductive to create a PNG file just to decode it again to raw data (like e.g. in https://github.com/xfce-mirror/tumbler/blob/master/plugins/ffmpeg-thumbnailer/ffmpeg-thumbnailer.c)

**Comment by dirkvdb** [comment]
You can now specify Rgb as image type, the buffer will then create the raw rgb data.
Unfortunately, with the current API the buffer will be allocated by the library so you would still have to potentially copy it depending on your use case.

**Comment by tomaszg7** [comment]
Great. Thank you. However I'm a bit unclear - C api doesn't tell me the exact height/width of a generated thumbnail, only `size`. In this way it is not possible to interpret the data in the buffer in a meaningful way. Am I missing something?

**Comment by dirkvdb** [comment]
You are right, the width height information was missing. I committed a change that adds with and height information to the image_data_struct.

**Comment by tomaszg7** [comment]
Now it works flawlessly with `gdk_pixbuf_new_from_data`. Thanks.
