### ISSUE TITLE
ffmpegthumbnailer don't work with cyrillic file's name

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dirkvdb/ffmpegthumbnailer#104]
```
to make ffmpegthumbnailer work after installation I had to create the file 
/usr/share/thumbnailers/ffmpeg.thumbnailer     and add there this code: 

[Thumbnailer Entry]
TryExec=ffmpegthumbnailer
Exec=ffmpegthumbnailer -s %s -i %u -o %o -c png -f -t 10
MimeType=video/flv;video/webm;video/mkv;video/mp4;video/mpeg;video/avi;video/ogg
;video/quicktime;video/x-avi;video/x-flv;video/x-mp4;video/x-mpeg;video/x-webm;v
ideo/x-mkv;application/x-extension-webm;video/x-matroska;video/x-ms-wmv;video/x-
msvideo;video/x-msvideo/avi;video/x-theora/ogg;video/x-theora/ogv;video/x-ms-asf
;video/x-m4v;

ffmpegthumbnailer don't show thumbnails for video files which have cyrillic 
symbols into the name. generally that problem occurs even for some video files 
without cyrillic symbols, in this case I didn't match any regularity.


ffmpegthumbnailer 2.0.7-2
Ubuntu 12.10 (quantal) x64
Linux 3.5.0-27-generic
GNOME 3.6.0
Nautilus 3.6.3
```

Original issue reported on code.google.com by `Sergi...@gmail.com` on 16 Apr 2013 at 12:52

Attachments:
- [Снимок экрана от 2013-04-07 10:58:30.png](https://storage.googleapis.com/google-code-attachments/ffmpegthumbnailer/issue-104/comment-0/Снимок экрана от 2013-04-07 10:58:30.png)

**Comment by uvwild** [comment]
BUMP!
so it seems this issue is still existing in new ubuntu 16.04

i configured  a  thumbnailer to redirect to my logging thumbnail generator but still get the
Error: Could not open input file:  xxxx.bla
(despite the quotes around the input filename in the thumbnailer config files)
calling the same command from the command line works though  !?!?!

i have 2 test cases
one with a space in a directory name  (from disk label and fuse)
and just simple spaces in the filenames

**Comment by uvwild** [comment]
I finally managed to fix it  ...What a f*cking drama...
**Please, if somebody has a better solution than this bloody hack let me know!!!**

I had to reparse the args  in my thumbnailer receiving the quoted $i param
then I could pass them on newly quoted to ffmpegthumbnailer...

I suppose this works now for most special characters now?!?!
Why is this quoting still such a bloody mess..... some how the quoted args end up in something like:
`''\''/my/file name/with quotes/and mayber other garbage''\''`
If you dont put the quotes around the %i param the spaces mess it up.
If you DO put the quotes the extra single quote is disturbing the parameter for ffmpegthumbnailer
**Thats why it DOES NOT work without the intermediate script just using the quoted arg.**

So in the redirector thumbmail like so:
Exec=mythumbnailer -s %s -i "%i" -o %o  -f 

The receiving thumbnailer deals with the quotes and calls the real one:
$cat mythumbnailer
```
#!/bin/bash
input=$(echo $2 | tr -d \')
output=$4
size=$6
ffmpthumbnailer -i "$input" -o $output -s $size -f

```
