### ISSUE TITLE
too much noise on stderr

### ISSUE THREAD

**Issue by IgnorantGuru** [dirkvdb/ffmpegthumbnailer#117]
This is a re-submission of a request I added to the old Google Code site.

The video_thumbnailer_generate_thumbnail_to_file() function sends a lot of output to stderr, resulting in thousands of lines of noise when generating thumbnails.  Use example [here](https://github.com/IgnorantGuru/spacefm/blob/ebdea761bb82e1d86ff73acef16eb2e58ae84759/src/vfs/vfs-thumbnail-loader.c#L449).

In a multi-threaded app it's not practical to close stderr, and even in a single thread it's probably time-consuming to keep closing and reopening it.  But for anyone trying to do so, this worked:

~~~~
// close stderr
int fd = dup(fileno(stderr));
close(fileno( stderr));

video_thumbnailer_generate_thumbnail_to_file( video_thumb, file_path, thumbnail_file );

// reopen stderr
dup2(fd, fileno(stderr));
close(fd);
~~~~

But would appreciate a multi-thread compatible fix for this that doesn't involve closing stderr.  2.0.10 had an entry in the ChangeLog about stderr, but someone on our team who tested it reported: "https://github.com/dirkvdb/ffmpegthumbnailer/commit/59522ca5e5097b6e6841fc5dd05f345a8c245cde is the commit of interest - just removes stderr output from a few places in ffmpegthumbnailer itself, rather than the ffmpeg code it wraps."

For example, if a 'verbose' setting could be added in the video_thumbnailer struct, I could test for the version of ffmpegthumbnailer in use and use the setting conditionally.

Thanks.

**Comment by dirkvdb** [comment]
Is the error logging you see coming from ffmpeg or from ffmpegthumbnailer?

**Comment by IgnorantGuru** [comment]
I don't know for sure but probably from ffmpeg.  They look like this (and they are displayed in different colors, brown and red):

~~~~
[mpeg4 @ 0x7fb4c89079c0] Invalid and inefficient vfw-avi packed B frames detected
[mpeg4 @ 0x7fb4c89079c0] frame skip 8
[mpeg4 @ 0x7fb4c810bfa0] Invalid and inefficient vfw-avi packed B frames detected
[mpeg4 @ 0x7fb4c830c6a0] header damaged
Failed to decode video frame: bytesDecoded < 0
~~~~

**Comment by IgnorantGuru** [comment]
Also, even though it produces all those errors, it still yields a good thumbnail, almost always.  So they don't seem to be of use except in some debug mode.

**Comment by dirkvdb** [comment]
I have just made a commit that allows you to set a log callback. If you do this, the library should be completely silent. It also intercepts the ffmpeg output now.

Feel free to check it out.

**Comment by IgnorantGuru** [comment]
Thanks.  Off-hand I don't see from the API how the set_callback function works without being passed the video_thumbnailer* pointer, or how it will know which thumbnailer to apply the callback to.  But we'll take a look.

Also for your consideration:  If your lib is intended for file managers which just want to generate thousands of thumbnails, I think a good default for this would be to silence the output.  Most use cases aren't going to be debugging ffmpeg via this thumbnailer lib.  For the few that are, they could set the callback.  Seems like a lot of noise for a default debug level relative to this API's purpose.  One nice thing here was the simplicity of the API, but now a callback function also has to be created and set, with no real gain.  I can't imagine any typical user wanting that output level.

Anyway just a thought - thanks for the response, and I or @OmegaPhil will let you know how this is working.

**Comment by dirkvdb** [comment]
The logging callback does not take the video_thumbnailer pointer because the ffmpeg log callback is global. I will invesigate if I can differentiate on the thumbnailer instance based on the arguments I receive from the ffmpeg callback. In that I could make the callback per instance, which would be nicer.

**Comment by OmegaPhil** [comment]
Thanks, I have implemented the current state of the code and it works here :)

**Comment by dirkvdb** [comment]
I have just pushed some changes to the logging callback mechanism.
You now register a callback per thumbnailer instance and by default no logging is generated.

I have completely disabled the internal ffmpeg logging as it wasn't really useful and could not be traced back to the thumbnailer instance properly.

I think this is an improvement over the initial version. Sorry to break your code :-)

**Comment by OmegaPhil** [comment]
I can't compile SpaceFM with this new library code:

```/usr/local/include/libffmpegthumbnailer/videothumbnailerc.h:45:5: error: unknown type name ‘thumbnailer_data’
     thumbnailer_data*       tdata;                  /* for internal use only */```

This is only defined in videothumbnailerc.cpp.

**Comment by dirkvdb** [comment]
Oops, I only tested with a c++ compiler. Please try the fix I just pushed

**Comment by OmegaPhil** [comment]
Sorry for the delay - something screwed up on the first try, for some reason no video thumbnails were being rendered, but now I try it now and its fine.

Thanks

**Comment by IgnorantGuru** [comment]
Sounds good - thanks!
