### ISSUE TITLE
emdedded cover art thumbnails

### ISSUE THREAD

**Issue by AcarBurak** [dirkvdb/ffmpegthumbnailer#122]
Is it possible to get the embedded mkv cover arts as thumbnails?

**Comment by dirkvdb** [comment]
No, ffmpegthumbnailer does not use video metadata

**Comment by AcarBurak** [comment]
All right, thank you.

**Comment by AcarBurak** [comment]
By chance I've found two years later that you've [added](https://github.com/dirkvdb/ffmpegthumbnailer/issues/138) it a year later since this issue.

Well done.
