### ISSUE TITLE
Tag for 2.1.0

### ISSUE THREAD

**Issue by rzurad** [dirkvdb/ffmpegthumbnailer#123]
Can we get a tag for release 2.1.0? I'd like to upgrade my production servers so they can reap the rewards of everything in that release (specifically the anamorphic fix and the quieter stdout/stderr so I can turn logging back on).

It's just nicer if I can use a tagged version instead of a specific commit hash.

Thanks! :)

**Comment by dirkvdb** [comment]
I will try to make the label in the coming days.

**Comment by dirkvdb** [comment]
I just created release 2.1.0

**Comment by rzurad** [comment]
Thanks! :)
