### ISSUE TITLE
ffmpegthumbnailer doesn't compile against current ffmpeg

### ISSUE THREAD

**Issue by phatgeek** [dirkvdb/ffmpegthumbnailer#124]
When compiling against ffmpeg cloned from the ffmpeg github repository:

In file included from /home/rich/Downloads/ffmpegthumbnailer-2.1.0/libffmpegthumbnailer/moviedecoder.cpp:17:0:
/home/rich/Downloads/ffmpegthumbnailer-2.1.0/libffmpegthumbnailer/moviedecoder.h:63:91: error: ‘PixelFormat’ has not been declared
     void createAVFrame(AVFrame** pAvFrame, uint8_t** pFrameBuffer, int width, int height, PixelFormat format);
                                                                                           ^
/home/rich/Downloads/ffmpegthumbnailer-2.1.0/libffmpegthumbnailer/moviedecoder.cpp: In member function ‘bool ffmpegthumbnailer::MovieDecoder::decodeVideoPacket()’:
/home/rich/Downloads/ffmpegthumbnailer-2.1.0/libffmpegthumbnailer/moviedecoder.cpp:280:40: error: ‘avcodec_get_frame_defaults’ was not declared in this scope
     avcodec_get_frame_defaults(m_pFrame);
                                        ^
/home/rich/Downloads/ffmpegthumbnailer-2.1.0/libffmpegthumbnailer/moviedecoder.cpp: In member function ‘void ffmpegthumbnailer::MovieDecoder::getScaledVideoFrame(int, bool, ffmpegthumbnailer::VideoFrame&)’:
/home/rich/Downloads/ffmpegthumbnailer-2.1.0/libffmpegthumbnailer/moviedecoder.cpp:329:88: error: ‘avpicture_deinterlace’ was not declared in this scope
                               m_pVideoCodecContext->width, m_pVideoCodecContext->height);
                                                                                        ^
/home/rich/Downloads/ffmpegthumbnailer-2.1.0/libffmpegthumbnailer/moviedecoder.cpp:333:26: error: ‘PIX_FMT_RGB24’ was not declared in this scope
     convertAndScaleFrame(PIX_FMT_RGB24, scaledSize, maintainAspectRatio, scaledWidth, scaledHeight);
                          ^
/home/rich/Downloads/ffmpegthumbnailer-2.1.0/libffmpegthumbnailer/moviedecoder.cpp: At global scope:
/home/rich/Downloads/ffmpegthumbnailer-2.1.0/libffmpegthumbnailer/moviedecoder.cpp:344:41: error: variable or field ‘convertAndScaleFrame’ declared void
 void MovieDecoder::convertAndScaleFrame(PixelFormat format, int scaledSize, bool maintainAspectRatio, int& scaledWidth, int& scaledHeight)
                                         ^
/home/rich/Downloads/ffmpegthumbnailer-2.1.0/libffmpegthumbnailer/moviedecoder.cpp:344:41: error: ‘PixelFormat’ was not declared in this scope
/home/rich/Downloads/ffmpegthumbnailer-2.1.0/libffmpegthumbnailer/moviedecoder.cpp:344:61: error: expected primary-expression before ‘int’
 void MovieDecoder::convertAndScaleFrame(PixelFormat format, int scaledSize, bool maintainAspectRatio, int& scaledWidth, int& scaledHeight)
                                                             ^
/home/rich/Downloads/ffmpegthumbnailer-2.1.0/libffmpegthumbnailer/moviedecoder.cpp:344:77: error: expected primary-expression before ‘bool’
 void MovieDecoder::convertAndScaleFrame(PixelFormat format, int scaledSize, bool maintainAspectRatio, int& scaledWidth, int& scaledHeight)
                                                                             ^
/home/rich/Downloads/ffmpegthumbnailer-2.1.0/libffmpegthumbnailer/moviedecoder.cpp:344:103: error: expected primary-expression before ‘int’
 void MovieDecoder::convertAndScaleFrame(PixelFormat format, int scaledSize, bool maintainAspectRatio, int& scaledWidth, int& scaledHeight)
                                                                                                       ^
/home/rich/Downloads/ffmpegthumbnailer-2.1.0/libffmpegthumbnailer/moviedecoder.cpp:344:121: error: expected primary-expression before ‘int’
 void MovieDecoder::convertAndScaleFrame(PixelFormat format, int scaledSize, bool maintainAspectRatio, int& scaledWidth, int& scaledHeight)
                                                                                                                         ^
/home/rich/Downloads/ffmpegthumbnailer-2.1.0/libffmpegthumbnailer/moviedecoder.cpp:453:1: error: expected ‘}’ at end of input
 }
 ^
make[2]: *** [CMakeFiles/libffmpegthumbnailer.dir/libffmpegthumbnailer/moviedecoder.cpp.o] Error 1
make[1]: *** [CMakeFiles/libffmpegthumbnailer.dir/all] Error 2
make: *** [all] Error 2

It appears that ffmpegthumbnailer is using a deprecated ffmpeg api.  As I understand it, the new variable is AVPixelFormat. and ffmpegthumbnailer should be updated.

**Comment by dirkvdb** [comment]
I changed the enum type, please try it against ffmpeg-git

**Comment by phatgeek** [comment]
Sorry for the delay... Yes, thanks I'll let you know..

**Comment by phatgeek** [comment]
I now get a different error related to declarations:

/home/rich/Downloads/ffmpegthumbnailer/libffmpegthumbnailer/moviedecoder.cpp: In member function ‘bool ffmpegthumbnailer::MovieDecoder::decodeVideoPacket()’:
/home/rich/Downloads/ffmpegthumbnailer/libffmpegthumbnailer/moviedecoder.cpp:280:40: error: ‘avcodec_get_frame_defaults’ was not declared in this scope
     avcodec_get_frame_defaults(m_pFrame);
                                        ^
/home/rich/Downloads/ffmpegthumbnailer/libffmpegthumbnailer/moviedecoder.cpp: In member function ‘void ffmpegthumbnailer::MovieDecoder::getScaledVideoFrame(int, bool, ffmpegthumbnailer::VideoFrame&)’:
/home/rich/Downloads/ffmpegthumbnailer/libffmpegthumbnailer/moviedecoder.cpp:329:88: error: ‘avpicture_deinterlace’ was not declared in this scope
                               m_pVideoCodecContext->width, m_pVideoCodecContext->height);
                                                                                        ^
/home/rich/Downloads/ffmpegthumbnailer/libffmpegthumbnailer/moviedecoder.cpp:333:26: error: ‘PIX_FMT_RGB24’ was not declared in this scope
     convertAndScaleFrame(PIX_FMT_RGB24, scaledSize, maintainAspectRatio, scaledWidth, scaledHeight);
                          ^
make[2]: *** [CMakeFiles/libffmpegthumbnailer.dir/libffmpegthumbnailer/moviedecoder.cpp.o] Error 1
make[1]: *** [CMakeFiles/libffmpegthumbnailer.dir/all] Error 2
make: *** [all] Error 2

...but that's progress. Does it compile for you?

**Comment by dirkvdb** [comment]
I didn't test my changes agains git ffmpeg. I was hoping changing the enum was sufficient :-)

I installed ffmpeg from git now and replacing the avpicture_deinterlace method will require a bit more investigation. Apparently the new filter graph mechanism needs to be used instead.

**Comment by phatgeek** [comment]
I believe so. :(

Thank you for your work.

**Comment by mrseth** [comment]
What is the latest version of ffmpeg this god damn thing will compile with?

**Comment by ambidot** [comment]
Arch linux here. I successfully built [`extra/ffmpegthumbnailer`](https://projects.archlinux.org/svntogit/packages.git/tree/trunk?h=packages/ffmpegthumbnailer) from this repo (modified `source` line) against `aur/ffmpeg-git-r76695.a62178b` (ca. 2015-11-16) with some changes.
* remove `archive/$pkgver.tar.gz` from the `source` line
* clone this repo to $srcdir/ffmpegthumbnailer-$pkgver manually
* replace `./{autogen.sh,configure}` with `cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DLIB_DEST_DIR=lib -DCMAKE_BUILD_TYPE=Release -DENABLE_GIO=ON -DENABLE_THUMBNAILER=ON .`
libffmpegthumbnailer/moviedecoder.cpp:
* comment out `avcodec_get_frame_defaults(m_pFrame);`
* comment out `if (m_pFrame->interlaced_frame) { avpicture_deinterlace(...) }`
* replace `PIX_FMT_RGB24` with `AV_PIX_FMT_RGB24`

The only side effect is that this kills deinterlacing. I don't know how to rewrite ffmt to use yadif and I don't have any interlaced videos so this will do.

**Comment by Ullaakut** [comment]
Yo guys.

I just cloned and compiled this repo smoothly, but trying to generate a thumbnail always gives me the error 'Error: Failed to get buffer from filter Resource temporarily unavailable'.

I tried with different files, different formats, and even the video_sample in test can't be thumbnailed.

Nice Nintendo advertising though :-)

**Comment by dirkvdb** [comment]
The Resource temporarily unavailable errors should be fixed now

**Comment by sxiii** [comment]
Greetings guys... Same problem arises for me. It has some errors:
```
In file included from /home/sw/fcomp/ffmpegthumbnailer/libffmpegthumbnailer/moviedecoder.cpp:32:
/usr/include/libavfilter/buffersink.h:76:21: note: declared here
   76 | AVBufferSinkParams *av_buffersink_params_alloc(void);
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/sw/fcomp/ffmpegthumbnailer/libffmpegthumbnailer/moviedecoder.cpp:394:27: warning: ‘void avfilter_register_all()’ is deprecated [-Wdeprecated-declarations]
  394 |     avfilter_register_all();
      |                           ^
In file included from /home/sw/fcomp/ffmpegthumbnailer/libffmpegthumbnailer/moviedecoder.cpp:31:
/usr/include/libavfilter/avfilter.h:714:6: note: declared here
  714 | void avfilter_register_all(void);
      |      ^~~~~~~~~~~~~~~~~~~~~
/home/sw/fcomp/ffmpegthumbnailer/libffmpegthumbnailer/moviedecoder.cpp: In member function ‘bool ffmpegthumbnailer::MovieDecoder::getVideoPacket()’:
/home/sw/fcomp/ffmpegthumbnailer/libffmpegthumbnailer/moviedecoder.cpp:577:9: error: ‘av_packet_unref’ was not declared in this scope; did you mean ‘av_frame_unref’?
  577 |         av_packet_unref(m_pPacket);
      |         ^~~~~~~~~~~~~~~
      |         av_frame_unref
/home/sw/fcomp/ffmpegthumbnailer/libffmpegthumbnailer/moviedecoder.cpp:591:17: error: ‘av_packet_unref’ was not declared in this scope; did you mean ‘av_frame_unref’?
  591 |                 av_packet_unref(m_pPacket);
      |                 ^~~~~~~~~~~~~~~
      |                 av_frame_unref
/home/sw/fcomp/ffmpegthumbnailer/libffmpegthumbnailer/moviedecoder.cpp: In member function ‘int32_t ffmpegthumbnailer::MovieDecoder::getStreamRotation()’:
/home/sw/fcomp/ffmpegthumbnailer/libffmpegthumbnailer/moviedecoder.cpp:647:90: error: ‘AV_PKT_DATA_DISPLAYMATRIX’ was not declared in this scope; did you mean ‘AV_FRAME_DATA_DISPLAYMATRIX’?
  647 | rpret_cast<int32_t*>(av_stream_get_side_data(m_pVideoStream, AV_PKT_DATA_DISPLAYMATRIX, nullptr));
      |                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                              AV_FRAME_DATA_DISPLAYMATRIX
/home/sw/fcomp/ffmpegthumbnailer/libffmpegthumbnailer/moviedecoder.cpp:647:50: error: ‘av_stream_get_side_data’ was not declared in this scope; did you mean ‘av_frame_get_side_data’?
  647 |     int32_t* matrix = reinterpret_cast<int32_t*>(av_stream_get_side_data(m_pVideoStream, AV_PKT_DATA_DISPLAYMATRIX, nullptr));
      |                                                  ^~~~~~~~~~~~~~~~~~~~~~~
      |                                                  av_frame_get_side_data
make[2]: *** [CMakeFiles/libffmpegthumbnailerobj.dir/build.make:82: CMakeFiles/libffmpegthumbnailerobj.dir/libffmpegthumbnailer/moviedecoder.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:204: CMakeFiles/libffmpegthumbnailerobj.dir/all] Error 2
make: *** [Makefile:182: all] Error 2
```

However, my system has ffmpegthumbnailer installed from the Arch repositories. I don't know if I can get the build instructions from it maybe...
