### ISSUE TITLE
[Feature Request] Matroska Cover

### ISSUE THREAD

**Issue by Addicted5** [dirkvdb/ffmpegthumbnailer#138]
Hi,
MkvToolnix support embedding cover art to mkv file.
Icaros in windows can show this as thumbnail in windows system.
How ever in Linux no way to take advantage of this Embedded cover art.
It would be great if ffmpegthumbnailer can extract this coverart for thumbnail.

**Comment by dirkvdb** [comment]
Can you provide me a link to a file that contains a cover, then I can see what's possible

**Comment by Addicted5** [comment]
here is 1 sample video.
i just added cover with mkvtoolnix & checked in windows (using icaros) if cover shown properly.
But In linux normal video thumbnail, not the cover art i added.
[sample.mkv](https://mega.nz/#!DJIi0JgZ!7p4_cqScOh3kgEI8kouWiU1eZgKLAvntgKGohKrDuV8)

**Comment by dirkvdb** [comment]
The embeddedcover branch contains an initial implementation of this feature.
An additional command line option -m is added. If this option is given, the embedded cover image will be used instead of the video content if it is found.

Feel free to try it out

**Comment by Addicted5** [comment]
finally all my movie collection looks alive in linux.
Thanks for your hard work.
it's working fine in arch.

**Comment by dirkvdb** [comment]
I released v2.2.0  containing this feature

**Comment by tomaszg7** [comment]
Since you're already updating library API, please consider adding a flag to produced `image_data` indicating whether the image comes from the stream or metadata.

**Comment by dirkvdb** [comment]
I committed a change that introduces the requested flag

**Comment by zeeshanali1993** [comment]
> finally all my movie collection looks alive in linux. Thanks for your hard work. it's working fine in arch.

I have installed ffmpegthumbnailer but now cover as a thumbnail. So any help appreciated.

**Comment by rieje** [comment]
@zeeshanali1993 It seems the `-m` option does not support webp covers which I'm also experiencing. There's an [open issue](https://github.com/dirkvdb/ffmpegthumbnailer/issues/216) here but no progress has been made.
