### ISSUE TITLE
ffmpegthumbnailer -t not working as expected

### ISSUE THREAD

**Issue by isuPatches** [dirkvdb/ffmpegthumbnailer#139]
I'm trying to create a thumbnail 3 seconds into a mp4 video I've transcoded.

`Running....ffmpegthumbnailer -c jpg -q 10 -s 175 -t 00:00:03.0 -a -i /<FILEPATH>/thumb_20160816182847.MP4 -o /<FILEPATH>/tmpfile.jpg`

The thumbnail is still showing second 0...what am I doing incorrectly?

The command is successful.

**Comment by dirkvdb** [comment]
Can you provide me a link to a failing sample. I can't reproduce it on my local files
