### ISSUE TITLE
"Error: Could not find video stream" on files encoded in MJPEG

### ISSUE THREAD

**Issue by MoonSweep** [dirkvdb/ffmpegthumbnailer#142]
Hi,

ffmpegthumbnailer 2.2.0 fails to generate thumbnails for all files encoded in MJPEG (either within mov or avi containers).

It exits with the message:

`Error: Could not find video stream`

...and generates an empty PNG file.

On the same system, ffmpeg 3.1.3 (via ffplay) can play these files correctly.

Regards,

-- 
Raphaël

**Comment by jkhsjdhjs** [comment]
I'm getting the same with png and jpg files

**Comment by dirkvdb** [comment]
I just pushed a fix that should fix this
