### ISSUE TITLE
Specify height of thumbnail instead of width

### ISSUE THREAD

**Issue by ccoffey** [dirkvdb/ffmpegthumbnailer#157]
The `-s: size` option seems to refer to the width of the thumbnail. Is there anyway to create a thumbnail by specifying a height instead?

I need to be able to create thumbnails with a fix height, regardless of their height!

**Comment by dirkvdb** [comment]
Well the size option specifies the maximum width OR height depending on the aspect ratio.
I'll think about a way to achieve what you want, probably through a more advanced -s value

**Comment by dirkvdb** [comment]
I made a commit that supports specifying the width or height explicitly.

`ffmpegthumbnailer -i i.mp4 -o test.png -s h=128`

**Comment by ccoffey** [comment]
This is really great! Thank you so much for finding the time to implement this!

**Comment by tomaszg7** [comment]
It would be nice to have this possibility also in library API.

**Comment by dirkvdb** [comment]
I added a thumbnail_size_string field to the video_thumbnailer_struct of the c API.
This allows size specifications similar to the cli.

e.g.: "h=128" or "h=200:w=300"

**Comment by tomaszg7** [comment]
Thank you for another prompt commit. Is it supposed to ignore aspect ratio when both `h` and `w` are set? I hoped that it would act more like a bounding box size into which the thumb has to fit. 

Moreover I understand that this syntax might be handy in cli, but in C api it is a mess to create a string to pass there, remember to free it afterwards. Wouldn't it be more elegant just to have two int fields?

**Comment by dirkvdb** [comment]
I agree that the change was suboptimal, so I did some rework which I think is better.
There is a new API call: `video_thumbnailer_set_size(int width, int height)`

You can specify value <= 0 for one of the two parameters to scale accordingly.

If both values are specified and maintain_aspect_ratio is 0, then the thumbnail will have exactly the specified size. If maintain_aspect_ratio is 1, the thumbnail will fit in the specified size maintaining the aspect ratio.

**Comment by dirkvdb** [comment]
I agree that the change was suboptimal, so I did some rework which I think is better.
There is a new API call: `video_thumbnailer_set_size(int width, int height)`

You can specify value <= 0 for one of the two parameters to scale accordingly.

If both values are specified and maintain_aspect_ratio is 0, then the thumbnail will have exactly the specified size. If maintain_aspect_ratio is 1, the thumbnail will fit in the specified size maintaining the aspect ratio.

**Comment by tomaszg7** [comment]
Great, works like charm.

**Comment by tomaszg7** [comment]
Hmm, I'm afraid something is still wrong. The function `video_thumbnailer_set_size` should accept values `(0,0)` as a way to request image in original size. Before the changes, setting `thumbnail_size = 0` had this effect. Now I cannot achieve it in any way. Setting only `thumbnail_size = 0` produces small thumbnail (128x128).

**Comment by dirkvdb** [comment]
I looked over the fact that 0 uses original width when applying the changes.
Should be fixed now

**Comment by tomaszg7** [comment]
Almost there. `video_thumbnailer_set_size` works well now, but setting `thumbnail_size = 0` still does not. Even though it is deprecated, I think it should work for backward compatibility.

BTW. Maybe you should add the information about (0,0) to the description in the header. Moreover if you really wish to deprecate `thumbnail_size`, why not use `__attribute__ ((deprecated("use video_thumbnailer_set_size() instead")))`?

**Comment by dirkvdb** [comment]
Should be fixed now. Thanks for the feedback

**Comment by tomaszg7** [comment]
Yep, works now as expected. Thanks.
