### ISSUE TITLE
Most efficient way to install on Windows 10

### ISSUE THREAD

**Issue by RailsCod3rFuture** [dirkvdb/ffmpegthumbnailer#167]
I was able to successfully install ffmpegthumbnailer through Ubuntu's W10 command line interface. The issue is, I cannot get it to run properly with my rails configuration. I believe that the ffmpegthumbnailer binary needs to be on my PATH, in order for it to work correctly with Rails. Can you suggest an approach or give a small tutorial?
Thanks!

**Comment by dirkvdb** [comment]
Are you running it from windows or within the Ubuntu environment?
If running from windows I think its better to build it with mingw.

**Comment by RailsCod3rFuture** [comment]
The Ubuntu App is stand alone, I guess. Currently, I am running Ruby/Ruby on Rails within Windows 10 development environment. Is there any documentation for making the ffmpegthumbnailer with mingw?

**Comment by dirkvdb** [comment]
check out [msys2](https://www.msys2.org). It contains all the dependencies for ffmpegthumbailer. Install them with pacman and then build ffmpegthumbnailer from source with cmake.

**Comment by Salted-Fish-Swimming** [comment]
> The Ubuntu App is stand alone, I guess. Currently, I am running Ruby/Ruby on Rails within Windows 10 development environment. Is there any documentation for making the ffmpegthumbnailer with mingw?

I tried to compile ffmpegthumbnailer win's version on msys2 but failed. Do you hava a binary file that is compiled successfully?
