### ISSUE TITLE
Wrong colours in thumbnails generated from 10 bit videos

### ISSUE THREAD

**Issue by thebodzio** [dirkvdb/ffmpegthumbnailer#169]
Colours in thumbnails generated from 10 bit videos are wrong. Inadvertently they have a strong greenish tint to them. Attached screenshot illustrates the issue.

![screenshot from 2018-10-27 23-06-53](https://user-images.githubusercontent.com/1129853/47609372-71afb180-da3d-11e8-8ed0-ab45a54a27e4.png)

**Comment by dirkvdb** [comment]
Closing this. Pull requests will be accepted
