### ISSUE TITLE
upside-down thumbnail created if video metadata specifies -180.00 degrees rotation

### ISSUE THREAD

**Issue by mfb** [dirkvdb/ffmpegthumbnailer#175]
I have a video with metadata specifying 180 degree rotation. However, in this case ffmpegthumbnailer doesn't rotate the video, resulting in an upside-down thumbnail.

The ffprobe output is:

```
    Metadata:
      rotate          : 180
      creation_time   : 2019-08-10T20:48:34.000000Z
      handler_name    : VideoHandle
    Side data:
      displaymatrix: rotation of -180.00 degrees
```

**Comment by dirkvdb** [comment]
can you debug it and check what 
```
auto rotation = getStreamRotation();
```
on line 428 of moviedecoder.cpp returns?

**Comment by mfb** [comment]
rotation = -1 

reading the code I think this makes sense, because it doesn't have any logic for values of 180 or -180

**Comment by mfb** [comment]
Well, it looks like there is code to handle this case in the master branch, but I am using the v2.2.0 release of ffmpegthumbnailer

**Comment by mfb** [comment]
Ok, I did some more testing and it looks like this bug is already fixed in the master branch, so maybe it's just time to roll a new release? :)

Note, I ran into a bug in the master branch: You have to specify -r0 or else it seems to keep sleeping (forever?) rather than exiting after creating the thumbnail.

**Comment by mfb** [comment]
Another bug in master branch: If I specify -o /home/directory/test.png I get
Error: Failed to open output file: ./home/directory/test.png.tmp

But -o test.png works if I run the command in /home/directory

**Comment by dirkvdb** [comment]
Closing this. Feel free to reopen
