### ISSUE TITLE
Doesn't work in nautilus after recent Arch upgrade

### ISSUE THREAD

**Issue by z0z0z** [dirkvdb/ffmpegthumbnailer#180]
https://bugs.archlinux.org/task/65135

Here's a bug issue on Arch's bug tracker.

Video thumbnails haven't been generating for about a week for me.

**Comment by dirkvdb** [comment]
I just installled the latest status in a docker container and was able to generate thubmnails using the ffmpegthumbnailer binary so I would need a better reproduction scenario.

**Comment by z0z0z** [comment]
That's just what some person on the Arch bug tracker said was at fault.

I've built ffmpeghtumbnailer myself against the current libs on my system (updated Arch) and it still doesn't work.

I really don't know why it doesn't work to be honest.

I know you could close this and just blame Arch, but it may be some new version of packages that eventually other distros will get too.

**Comment by dirkvdb** [comment]
But I installed the latest packages in an arch distribution

**Comment by z0z0z** [comment]
Hmmm, maybe it's something old left from previously existing systems after upgrade?

I really don't know, I'm not the only one experiencing this though.

If you have any idea at all what could be causing this, we'd appreciate it.

**Comment by dirkvdb** [comment]
I'm confused by the issue. It says downgrading gst-plugins-ugly fixes it, which is not a dependency of ffmpegthumbnailer. So it does not seem to be something I can fix.

**Comment by z0z0z** [comment]
Yeah the bug report blamed an upgrade of all 3 gst-plugins-ugly, x264, and ffmpeg

I think he just wasn't sure what actually caused this. I'll change the title.

**Comment by z0z0z** [comment]
This is fixed after latest Arch update.

Sorry no clue what even broke this on Arch's end, I'll close.
