### ISSUE TITLE
kffmpegthumnailer adds a border to thumbnails

### ISSUE THREAD

**Issue by TiGR** [dirkvdb/ffmpegthumbnailer#184]
When I generate thumbnail manually with `ffmpegthumbnailer`, I get this:
![12ccbc4fd0eb5b30988673dff2e4bb12](https://user-images.githubusercontent.com/281226/82705656-bd115c80-9c80-11ea-93ac-18ead3d6ba26.png)

But `kffmpegthumbnailer` adds a border:
![a2a6eb2762db37e348d5f153870fba74](https://user-images.githubusercontent.com/281226/82705677-c8fd1e80-9c80-11ea-8096-45ce6b38c372.png)

Both files were taken from `~/.cache/thumbnails/normal/`. In dolphin it looks like this:
![image](https://user-images.githubusercontent.com/281226/82705771-f6e26300-9c80-11ea-826a-bbe6eed0106b.png)

I was trying to find anything related to borders in that code, but was unable to.

**Comment by dirkvdb** [comment]
What are the sizes of the two thumbnails?

**Comment by TiGR** [comment]
Both images are 96x128 pixels

**Comment by TiGR** [comment]
Okay, I've added a pull request with a fix. @dirkvdb Please, take a look at it and also at my other pull requests. Thanks.
