### ISSUE TITLE
Thumbnails wrong orientation for images

### ISSUE THREAD

**Issue by St3ll4rM4n** [dirkvdb/ffmpegthumbnailer#185]
ffmpegthumbnailer is used in Gerbera UPNP server.
It works great.

However, when used on images the portrait type of images are converted to landscape thumbnails and they are rotated.
Can this be controled or/and fixed?

Additional info on Gerbera GITBUB
https://github.com/gerbera/gerbera/issues/864

**Comment by dirkvdb** [comment]
I have no time to investigate this, I will accept pull requests to fix this

**Comment by whitesnake-pl** [comment]
Any update on that?

**Comment by ggolda** [comment]
Faced the same problem. Extracted images for portrait oriented video files are rotated on 90 degrees. Any way to prevent this and scale them instead?

**Comment by whitesnake-pl** [comment]
@dirkvdb is there a chance this will be fixed soon? As mentioned this is being used by Gerbera but is not working as expected. If project is not developing anymore then maybe Gerbera team should explore other alternatives. Just need a clear statement. Thanks.

**Comment by dirkvdb** [comment]
> I have no time to investigate this, I will accept pull requests to fix this

@whitesnake-pl  As I stated before. I will currently only accept pull requests and will not perform any investigation myself.
