### ISSUE TITLE
ffmpegthumbnailer not working on Samba share

### ISSUE THREAD

**Issue by ln00** [dirkvdb/ffmpegthumbnailer#188]
Running Debian Buster GNOME latest version. Thumbnails work on local drives. Files on smb:// shares never display thumbnails. Tested on Nautilus and Thunar.

**Comment by dirkvdb** [comment]
Can you get a thumbnail with ffmpegthumbnailer command line?
Can you play smb:// with ffmpeg.

Ffmegthubnailer relies on ffmpeg for opening the files

**Comment by ln00** [comment]
Can you get a thumbnail with ffmpegthumbnailer command line?

Output: 
```
Not a native file, thumbnailing will likely fail: smb://192.168.1.1/seagate/4 tabling skai 25-50 part1.avi
Error: Could not open input file: smb://192.168.1.1/seagate/4 tabling skai 25-50 part1.avi
```

**Comment by ln00** [comment]
Can you play smb:// with ffmpeg?

Output:
```
smb://192.168.1.1/seagate/4 tabling skai 25-50 part 1.avi: Protocol not found
Did you mean file:smb://192.168.1.1/seagate/4 tabling skai 25-50 part 1.avi?
```

**Comment by dirkvdb** [comment]
You need to figure out if your ffmpeg is compiled with samba support
