### ISSUE TITLE
New kffmpegthumbnailer version

### ISSUE THREAD

**Issue by TiGR** [dirkvdb/ffmpegthumbnailer#193]
@dirkvdb I'm starting process of bringing kffmpegthumnailer back into debian, but the first thing that is required to do is to make new stable version of it. Could you bump the version up? It hasn't been developed for over 11 years, and now new version bump is quite worth a version bump, maybe up to 1.2.0 or even 2.0.0.

So how could this be achieved? By updating Changelog file? As I see no tags for kffmpegthumbnailer.

**Comment by dirkvdb** [comment]
Version 1.2.0 seems fine to me. No kffmpethumbnailer tags have been created yet.
I'm happy to accept a pull request, but I do not have the time to perform any testing, so I will trust you have tested it.

**Comment by TiGR** [comment]
@dirkvdb Okay, I've created the pull request. As of testing, me and my friends use it on daily basis for quite some time now. No problems encountered yet.
