### ISSUE TITLE
Extracting cover don’t seems to work with webp covers

### ISSUE THREAD

**Issue by Br31zh** [dirkvdb/ffmpegthumbnailer#216]
I have a bunch of MVK videos with cover, I’m using the -m option to see them, but it seems that if the embedded cover is in webp format, it generate a normal cover instead of using it.

If the cover is in jpg format, it’s working well.

**Comment by rieje** [comment]
I am experiencing the same issue, videos downloaded with `yt-dlp --embed-thumbnails` do not show the embedded thumbnails despite the `-m` option.

**Comment by Br31zh** [comment]
Since webp images aren’t really supported, I use `--convert-thumbnails "webp>jpg"` for `yt-dlp` now, so it convert webp to jpg and then it works… at least that’s a workaround.

**Comment by dirkvdb** [comment]
Closing this. Pull requests will be accepted

**Comment by dirkvdb** [comment]
Pull requests will still be accepted
