### ISSUE TITLE
Can I use this in iOS with ffmpeg-kit ?

### ISSUE THREAD

**Issue by FlashTang** [dirkvdb/ffmpegthumbnailer#219]
Hi 
I use such command to  generate thumbnails
ffmpeg -ss 00:00:05 -i input.mp4 -frames:v 1 frame_1.png
this command is fast ,but if I want to generate multi  thumbnails (e.g. 10 thumbnails) , it will be slow (on iOS)
So I want to know :  can ffmpegthumbnailer work on iOS ?

**Comment by dirkvdb** [comment]
If you manage to cross compile the dependencies I see no reason why this should't work on ios
