### ISSUE TITLE
ffmpegthumbnailer does not return an error code

### ISSUE THREAD

**Issue by Zakret** [dirkvdb/ffmpegthumbnailer#221]
When I pass incorrectly unforeseen arguments to the ffmpegthumbnailer, I should get an error, but instead I get a first frame of video. Because of this behavior, I can get the wrong impression that my input is handled in accordance with my  expectations.

e.g.
>ffmpegthumbnailer -t clearly wrong input -i ./input.mp4 -o ./output.jpg

Result: no error and output is a first frame of input.mp4

**Comment by dirkvdb** [comment]
Fixed in 256409b
