### ISSUE TITLE
(Feature Request) Add flag to grab cover from Matroska files as is

### ISSUE THREAD

**Issue by ProNoob135** [dirkvdb/ffmpegthumbnailer#222]
Since many video files already contain a thumbnail, generating a new one may not be preferred
Matroska thumbnails are simply encoded as  an attachment stream with the `filename` tag set to "cover.(jpg|png)",
which can be grabbed from the file with `-map 0:m:filename:cover.jpg` (or `png`)
A flag to prefer this over generating a new thumbnail (falling back otherwise) would replace the need for other thumbnailers(for Matroska atleast), possibly with an alternate flag to force this method without falling back
It's not as easy(or even possible) to get thumbnails from some other formats in ffmpeg unfortunately, but this would be a start

**Comment by Goosegit11** [comment]
What about `-m` flag?

>  -m      : prefer embedded image metadata over video content

**Comment by dirkvdb** [comment]
Pull requests can be accepted. I have no time to implement new features
