### ISSUE TITLE
Errno::ENOENT (No such file or directory) in Heroku

### ISSUE THREAD

**Issue by ghost** [dirkvdb/ffmpegthumbnailer#226]
Failed to upload thumb in dokku using rails 7 and ruby 3
gem 'carrierwave'
gem 'carrierwave-video-thumbnailer'
gem "mini_magick"

https://github.com/shunjikonishi/heroku-buildpack-ffmpeg
https://github.com/johnklawlor/heroku-buildpack-ffmpeg-thumbnailer
https://github.com/heroku/heroku-buildpack-ruby

Failed to thumbnail with ffmpegthumbnailer. Check ffmpegthumbnailer install and verify video is not corrupt. Original error: No such file or directory @ rb_file_s_rename -

app/vendor/ffmpegthumbnailer instead of this vendor/ffmpegthumbnailer its missing /app/ at the beginning;

**Comment by dirkvdb** [comment]
Closing. Not enough information. Feel free to reopen
