### ISSUE TITLE
Error: basic_string::substr: __pos (which is ...

### ISSUE THREAD

**Issue by Goosegit11** [dirkvdb/ffmpegthumbnailer#228]
Related: #223 

OS: Arch Linux
Repository      : extra
Name            : ffmpegthumbnailer
Version         : 2.2.2-5

% ffmpegthumbnailer -i "$f" -o bob
Error: basic_string::substr: __pos (which is 18446744073709551614) > this->size() (which is 3)

**Comment by Goosegit11** [comment]
Probleb fixed. What about making a new release?

**Comment by mrmbernardi** [comment]
@Goosegit11 What is your use case? The problem only arises with short filenames. Try `bob1234` instead of `bob`
